### ISSUE TITLE
Walk-through Register demonstrator 18/01/2021

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/registry-api#11]
https://demo.netwerkdigitaalerfgoed.nl/register/ (en https://demo.netwerkdigitaalerfgoed.nl/register-api/)
triple store op tijdelijk adres https://graphdb.ddeboer.nl/ (wordt https://graphdb.netwerkdigitalerfgoed.nl/)

NB: Huidige demonstrator toont minimale werking van de API. Er is nog geen crawler, dus datasetbeschrijvingen worden direct opgehaald (en niet frequent gecontroleerd voor update/delete).

**1 - Datasetbeschrijving aanmelden**

**1.1 - ... via URL van datasetbeschrijving**

**Actie**: Voer een URL in (*) en klik op knop.
**Resultaat**: De URL wordt opgeslagen  en de datasetbeschrijving wordt opgehaald en (in deze demonstrator) direct opgehaald en opgeslagen in de triple store.
**Controle**: weergave status code plus dataset opzoeken in stap 2.2.

(*) URL's:

- https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2.html (202)
- https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2a.html (400, missing creator)
- https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2b.html (400, missing distributions)
- https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2c.html (404)
- https://www.openarch.nl/datasets/ade
- https://www.openarch.nl/datasets/ghn
- https://demo.netwerkdigitaalerfgoed.nl/register/dataset.php?guid=... ([via](https://demo.netwerkdigitaalerfgoed.nl/register/list.php))
	
**1.2 - ... via formulier van datasetbeschrijving**

**Actie**: Vr een gegevens in (of klik op "voorbeelddata") op alle tabbladen, klik op knop op laatste tabblad.
**Resultaat**: De gegevens worden opgeslagen (in bestandsvorm) in het testregister en de URL hiervan wordt aangemeld via API (waardoor net als in 1.1 de datasetbeschrijving wordt opgehaald en (in deze demonstrator) direct opgehaald en opgeslagen in de triple store).
**Controle**: datasetbeschrijving opzoeken in stap 2.1 en stap 2.2.

**2 - Datasetbeschrijvingen doorzoeken**

**2.1 - ... lokaal opgeslagen in bestanden**

**Actie**: Toon overzicht, klik datasetbeschrijving aan.
**Resultaat**: Inhoud van datasetbeschrijving wordt getoond.

**2.2 - ... opgeslagen in triplestore**

**Actie:** Klik op triple store knop en voer (saved) SPARQL queries uit.
**Resultaat**: Eén of meer URI's van datasetbeschrijvingen

**Comment by ddeboer** [comment]
@coret The API is up again at https://demo.netwerkdigitaalerfgoed.nl/register-api

**Comment by coret** [comment]
@ddeboer de demo is goed gegaan, men was onder de indruk van het ons werk!
