### ISSUE TITLE
Fetch dataset description from URL

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/registry-api#2]
* Follows #1.
* Store description in #6.
* https://docs.google.com/document/d/1-E4DIwlzbL8Esv5YtHbVUXkT_U3pCprFDSI-hjiKf90/edit#heading=h.8gfp7ueu4w2k

**Comment by ddeboer** [comment]
Just like in the Network of Terms, we may want to use a `CONSTRUCT` here to select the data relevant to the Register, that is, find one or more dataset IRIs and their triples in the RDF data.

To test queries locally, see https://comunica.dev/docs/query/getting_started/query_cli/:

```
comunica-sparql https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2.html 'SELECT * { ?s ?p ?o }
```

```
comunica-sparql https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2.html 'CONSTRUCT WHERE { ?s a schema:Dataset. ?s schema:name ?name. ?s schema:creator ?creator. ?creator schema:name ?creator_name. ?creator ?url ?creator_url .  } '
```

**Comment by coret** [comment]
@ddeboer I created an issue at communica: https://github.com/comunica/comunica/issues/773

Did I describe the issue correctly: uncorrelated blank nodes (I don't see an "explosion" of repeated blank nodes, or at least, can't reproduce it). Is there a link with https://github.com/w3c/sparql-12/issues/87 ?

**Comment by ddeboer** [comment]
@coret Try it with creator _and_ distributions:

```
comunica-sparql https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2.html 'CONSTRUCT WHERE { ?s a schema:Dataset. ?s schema:distribution ?d. ?d ?p ?o. ?s schema:name ?name. ?s schema:creator ?creator. ?creator schema:name ?creator_name. ?creator ?url ?creator_url.  } '
```
