### ISSUE TITLE
http (notice missing s) pages with dataset descriptions should be processed

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/registry-api#21]
Test URL: http://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2.html

Result: 500

{"statusCode":500,"code":"ERR_INVALID_PROTOCOL","error":"Internal Server Error","message":"Protocol \"http:\" not supported. Expected \"https:\""}

**Comment by coret** [comment]
Additionally: URL should be followed when redirected (eg. to https version)

**Comment by ddeboer** [comment]
Really low prio IMHO, because anyone still on HTTP has other problems than our API.

(FYI, https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2.html works fine.)

**Comment by coret** [comment]
Low prio indeed.

It's just I was surprised about this restriction as it is not in the design, the design only speaks of an "allowed domain names" list. Can't find the https requirement in our code, is it a communica thing?

(BTW http://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2.html correctly redirects to https via a HTTP/1.1 308 Permanent Redirect, hence my not about following redirections).

**Comment by coret** [comment]
Response from tester (from KB):

> Overigens klaagt de demonstrator als je niet-https urls opgeeft. De pagina’s op data.bibliotheken zijn als het noodzakelijk is ook met https op te vragen maar in principes gebruiken we http-URIs (LODview laat bijvoorbeeld ook geen inverse relaties zien als je een https-variant opvraagt).

**Comment by ddeboer** [comment]
Of course, the IRIs can be HTTP as long as the URLs where we retrieve the descriptions are HTTPS.

**Comment by ddeboer** [comment]
@coret Do you have an example of a (valid) dataset at a HTTP URL? (http://data.bibliotheken.nl doesn’t work because of #31).

**Comment by coret** [comment]
http://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2.html is an example with redirection, just tested, API has no problem with this variant.
The same file at http://lab.coret.org/tmp/2.html (no redirection) also shows no problem (HTTP 200 on validation).

**Comment by ddeboer** [comment]
Ok, so HTTP works fine now.
