### ISSUE TITLE
Direct RDF input

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/registry-api#24]
There's a strong wish to make it possible to provide RDF directly. Getting dataset descriptions from a back-end system is a first step, publishing this in the right format on a webpage is a (for organisations hard) second step.

So besides the scraping of embedded RDF from a page, the Fetch component should also be able to process RDF directly from the provived URL, preferrable content-negotiation based.

To test this feature the following URL can be used with content-negotiation: http://data.bibliotheken.nl/id/dataset/nbt
```
curl -L  http://data.bibliotheken.nl/id/dataset/nbt    (-L for following redirect)
curl -LH "Accept: application/n-triples"  http://data.bibliotheken.nl/id/dataset/nbt
curl -LH "Accept: text/turtle" http://data.bibliotheken.nl/id/dataset/nbt
curl -LH "Accept: application/ld+json"  http://data.bibliotheken.nl/id/dataset/nbt
curl -LH "Accept: application/rdf+xml"  http://data.bibliotheken.nl/id/dataset/nbt
```

The various RDF flavors can also be requested without content-negotiation, like:
- http://data.bibliotheken.nl/doc/dataset/nbt.ttl
- http://data.bibliotheken.nl/doc/dataset/nbt.rdf
- http://data.bibliotheken.nl/doc/dataset/nbt.json
- http://data.bibliotheken.nl/doc/dataset/nbt.nt

Note: above URL's are also available on https

**Comment by ddeboer** [comment]
> So besides the scraping of embedded RDF from a page, the Fetch component should also be able to process RDF directly from the provived URL, preferrable content-negotiation based.

This _should_ already be possible.

**Comment by coret** [comment]
Yes:
```Status: 500

{"statusCode":500,"code":"ERR_INVALID_PROTOCOL","error":"Internal Server Error","message":"Protocol \"http:\" not supported. Expected \"https:\""}
```

**Comment by coret** [comment]
Sorry, should have beter read the message... But the https links says:
```
Status: 404

No dataset description found at https://data.bibliotheken.nl/doc/dataset/nbt.ttl
```

Which is odd, because the data does exist at this URL (same for .rdf and .nt)
