### ISSUE TITLE
GraphDB OOMs

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/registry-api#43]
We have [3,719,353 statements](https://triplestore.netwerkdigitaalerfgoed.nl) so 1.2 GB memory should be sufficient [according to the GraphDB docs](https://graphdb.ontotext.com/documentation/free/requirements.html#requirements-recommended). However, GraphDB keeps crashing with OOMs.

I’ve tried to give GraphDB 2 GB and even 3 GB, but the OOMs still occur when a larger amount of datasets (for instance from a catalog) are persisted.

Options:

- optimize our GraphDB configuration
- get larger nodes at our Kubernetes cluter
- ditch GraphDB and look for a more efficient RDF store.

**Comment by coret** [comment]
looking around for possible optimizations, like https://stackoverflow.com/questions/52587944/graphdb-outofmemoryerror-java-heap-space which suggests _decreasing_ GDB_HEAP_SIZE ([current setting = 3GB](https://github.com/netwerk-digitaal-erfgoed/infrastructure/blob/master/k8s/graphdb/graphdb-deployment.yml)).

additional option: ask help/ post issue @ ontotext

**Comment by ddeboer** [comment]
During updates, GraphDB just restarts:

```
[INFO ] 2021-02-03 08:23:43,754 [repositories/registry | o.e.r.h.s.r.g.GraphController] PUT data in graph
[INFO ] 2021-02-03 08:23:43,756 [repositories/registry | o.e.r.h.s.r.g.GraphController] no base URI specified, using 'https://www.openarch.nl/id/dataset_svp'
[INFO ] 2021-02-03 08:23:43,770 [repositories/registry | o.e.r.h.s.r.g.GraphController] PUT data in graph
[INFO ] 2021-02-03 08:23:43,770 [repositories/registry | o.e.r.h.s.r.g.GraphController] no base URI specified, using 'https://www.openarch.nl/id/dataset_brd'
[INFO ] 2021-02-03 08:23:48,205 [main | c.o.g.Config] Using 'jar:file:/opt/graphdb/dist/lib/graphdb-application-common-9.5.0.jar!/com/ontotext/graphdb/logback.xml' as logback's configuration file for graphdb
[INFO ] 2021-02-03 08:23:49,059 [main | c.o.g.s.GraphDB] Starting GraphDB in workbench mode.
[INFO ] 2021-02-03 08:24:04,216 [main | c.o.g.Config] GraphDB Home directory: /opt/graphdb/home
[INFO ] 2021-02-03 08:24:04,216 [main | c.o.g.Config] GraphDB Config directory: /opt/graphdb/home/conf
[INFO ] 2021-02-03 08:24:04,217 [main | c.o.g.Config] GraphDB Data directory: /opt/graphdb/home/data
[INFO ] 2021-02-03 08:24:04,217 [main | c.o.g.Config] GraphDB Work directory: /opt/graphdb/home/work
[INFO ] 2021-02-03 08:24:04,217 [main | c.o.g.Config] GraphDB Logs directory: /opt/graphdb/home/logs
[WARN ] 2021-02-03 08:24:05,527 [main | o.e.r.s.h.DirectoryLockManager] Removing invalid lock 1@graphdb-85df4ddbc-nm7cl
[INFO ] 2021-02-03 08:24:14,239 [main | c.o.g.s.GraphDB] Started GraphDB in workbench mode at port 7200.
```

**Comment by ddeboer** [comment]
Reducing the heap size to `1g` while raising the memory limit to `3Gi` seems to have brought some improvement.

**Comment by ddeboer** [comment]
Added some limits _and_ increased the cluster’s available memory, so we should be good for now.
