### ISSUE TITLE
Store dataset descriptions

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/registry-api#6]
### Questions

- In an RDF/Graph store. Perhaps TriplyDB? [Ways to get data into Triply](https://triply.cc/docs/triply-db-getting-started#adding-data) seem to be limited, but adding data by URL may be useful.
- How do we remove old data? Probably using [SPARQL Update](https://www.w3.org/TR/sparql11-update/#deleteData). Does Triply support this? Or do we have to switch to an RDF Store that does, such as Virtuoso?
- Alternatively, would it make sense to re-create the full Registry dataset each night, tagging the new one with a date (or replacing the old one)?

**Comment by coret** [comment]
For the pilot **Ontotext GraphDB** will be used as triple store. 

See https://github.com/Ontotext-AD/graphdb-docker for docker instructions (extra attention for volume for persistence).

Via the web-based GUI the initial configuration has to be set:
1. Create a new repository via Setup > Repositories (attention for Storage folder field)
2. Set admin password via Setup > Users and Access, set Security to On and Free Access to On (and select the repository created in 1..).
3. Set autocomplete to On via Setup > Autocomplete (not must, but nice)

**Comment by ddeboer** [comment]
In the future we may also want to look at [TerminusDB](https://terminusdb.com), which looks really interesting and ships with ready-to-use Docker images without registration blabla (as is required with GraphDB). Great JS support. But no SPARQL ([for good reasons](https://terminusdb.com/docs/frequently-asked-questions/#why-do-you-use-woql---web-object-query-language)), so we would have to dump HDT files for read-only SPARQL clients.

**Comment by coret** [comment]
At this moment, each dataset description is stored in a separate graph where the identifier of the graph is used as graph name.
I see the benefit  of this approach for updates. Any downsides to this approach?

**Comment by ddeboer** [comment]
Yes, I did this to make updates (and removals) easier. 

GraphDB searches through multiple graphs just fine, so I don’t see any downsides.
